In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('./train-2.csv')

In [5]:
df.head()

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО
0,0,1,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,22041969.33
1,0,2,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23268490.57
2,0,3,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,24487732.21
3,0,4,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23981980.29
4,0,5,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,26608343.78

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206150 entries, 0 to 206149
Data columns (total 19 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   new_id                                     206150 non-null  int64
 1   Месяц                                      206150 non-null  int64
 2   Дата открытия, категориальный              206150 non-null  object
 3   Торговая площадь, категориальный           206150 non-null  object
 4   Населенный пункт                           206150 non-null  object
 5   Регион                                     206150 non-null  object
 6   Численность населения                      206150 non-null  int64
 7   Количество домохозяйств                    206150 non-null  int64
 8   Трафик пеший, в час                        206150 non-null  int64
 9   Трафик авто, в час                         206150 non-null  int64
 10  Маркетплейсы, доставки, постаматы (100 м)  206150 non-null  int64
 11  Медицинские уч. и аптеки (300 м)           206150 non-null  int64
 12  Школы (300 м)                              206150 non-null  int64
 13  Остановки (300 м)                          206150 non-null  int64
 14  Продуктовые магазины (500 м)               206150 non-null  int64
 15  Пятерочки (500 м)                          206150 non-null  int64
 16  Количество касс                            206150 non-null  int64
 17  Флаг алкогольной лицензии                  206150 non-null  int64
 18  РТО                                        206150 non-null  float64
dtypes: float64(1), int64(14), object(4)
memory usage: 29.9+ MB

In [8]:
df.describe()

,new_id,Месяц,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО
count,206150.000000,206150.000000,2.061500e+05,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,206150.000000,2.061500e+05
mean,10367.410284,5.500000,1.193977e+06,3569.167111,129.692505,203.562163,1.905554,1.706767,0.426631,1.551346,3.876837,0.939801,7.503614,0.935435,3.272725e+07
std,6013.973290,2.872288,3.027519e+06,2956.914276,82.051663,206.585845,2.055777,2.201899,0.772145,2.410584,3.121435,1.202924,3.043850,0.245757,1.768909e+07
min,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.619487e+04
25%,5167.000000,3.000000,1.724400e+04,920.000000,83.000000,74.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,5.000000,1.000000,2.086432e+07
50%,10336.000000,5.500000,1.308440e+05,3076.000000,120.000000,139.000000,1.000000,1.000000,0.000000,0.000000,3.000000,1.000000,7.000000,1.000000,2.791845e+07
75%,15526.000000,8.000000,7.468300e+05,5507.000000,164.000000,261.000000,3.000000,3.000000,1.000000,3.000000,6.000000,2.000000,9.000000,1.000000,3.923328e+07
max,21430.000000,10.000000,1.653157e+07,24733.000000,1119.000000,3208.000000,19.000000,24.000000,9.000000,36.000000,21.000000,10.000000,32.000000,1.000000,2.205870e+08

In [10]:
df.columns.tolist()

['new_id',
 'Месяц',
 'Дата открытия, категориальный',
 'Торговая площадь, категориальный',
 'Населенный пункт',
 'Регион',
 'Численность населения',
 'Количество домохозяйств',
 'Трафик пеший, в час',
 'Трафик авто, в час',
 'Маркетплейсы, доставки, постаматы (100 м)',
 'Медицинские уч. и аптеки (300 м)',
 'Школы (300 м)',
 'Остановки (300 м)',
 'Продуктовые магазины (500 м)',
 'Пятерочки (500 м)',
 'Количество касс',
 'Флаг алкогольной лицензии',
 'РТО']

In [12]:
df.loc[df['Месяц'] == 10]

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО
9,0,10,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,27145282.92
19,1,10,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,1,2,2,3,6,1,9,1,32336271.96
29,2,10,Средний по возрасту,Маленький,Дубна г,Московская обл,75056,2050,80,144,11,0,1,1,0,0,7,1,37473470.94
39,3,10,Средний по возрасту,Большой,Подольск г,Московская обл,354166,3460,133,473,2,6,0,3,4,0,8,1,69136935.96
49,4,10,Средний по возрасту,Средний,Москва г,Москва г,12706550,6255,117,302,2,5,0,11,8,3,11,1,42004513.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206109,21414,10,Новый,Средний,Волжский г,Волгоградская обл,346036,3385,92,225,0,1,0,1,4,2,11,1,20977814.53
206119,21419,10,Новый,Средний,Волгоград г,Волгоградская обл,979623,3077,229,139,0,0,0,2,4,2,5,1,21912072.40
206129,21421,10,Новый,Большой,Волгоград г,Волгоградская обл,968504,4764,104,129,0,2,0,2,6,3,9,1,28346454.52
206139,21427,10,Новый,Большой,Волгоград г,Волгоградская обл,1115129,3431,170,190,0,0,0,0,11,2,8,1,18769628.66
206149,21430,10,Новый,Средний,Волгоград г,Волгоградская обл,1113134,4202,387,149,1,1,2,2,3,1,7,1,23504693.28

In [15]:
df = df.sort_values(['new_id', 'Месяц'])

In [16]:
df.head()

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО
0,0,1,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,22041969.33
1,0,2,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23268490.57
2,0,3,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,24487732.21
3,0,4,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23981980.29
4,0,5,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,26608343.78

In [21]:
df['rto_lag_1'] = df.groupby('new_id')['РТО'].shift(1)

In [20]:
df.head(12)

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО,lag_1
0,0,1,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,22041969.33,NaN
1,0,2,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23268490.57,22041969.33
2,0,3,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,24487732.21,23268490.57
3,0,4,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23981980.29,24487732.21
4,0,5,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,26608343.78,23981980.29
5,0,6,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,26148681.55,26608343.78
6,0,7,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,27292985.79,26148681.55
7,0,8,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,27712633.36,27292985.79
8,0,9,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,24366310.39,27712633.36
9,0,10,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,27145282.92,24366310.39
10,1,1,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,1,2,2,3,6,1,9,1,21881376.19,NaN
11,1,2,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,1,2,2,3,6,1,9,1,24370168.15,21881376.19

In [22]:
df['rto_lag2'] = df.groupby('new_id')['РТО'].shift(2)

In [23]:
df['rto_mean_lag6'] = df.groupby('new_id')['РТО'].shift(1).rolling(6).mean()

In [25]:
df.head(12)

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",...,Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО,lag_1,rto_lag_1,rto_lag2,rto_mean_lag6
0,0,1,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,22041969.33,NaN,NaN,NaN,NaN
1,0,2,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,23268490.57,22041969.33,22041969.33,NaN,NaN
2,0,3,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,24487732.21,23268490.57,23268490.57,22041969.33,NaN
3,0,4,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,23981980.29,24487732.21,24487732.21,23268490.57,NaN
4,0,5,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,26608343.78,23981980.29,23981980.29,24487732.21,NaN
5,0,6,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,26148681.55,26608343.78,26608343.78,23981980.29,NaN
6,0,7,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,27292985.79,26148681.55,26148681.55,26608343.78,2.442287e+07
7,0,8,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,27712633.36,27292985.79,27292985.79,26148681.55,2.529804e+07
8,0,9,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,24366310.39,27712633.36,27712633.36,27292985.79,2.603873e+07
9,0,10,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,2,0,10,1,27145282.92,24366310.39,24366310.39,27712633.36,2.601849e+07
10,1,1,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,3,6,1,9,1,21881376.19,NaN,NaN,NaN,NaN
11,1,2,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,3,6,1,9,1,24370168.15,21881376.19,21881376.19,NaN,NaN

In [26]:
df.drop(['lag_1'], axis = 1, inplace = True)

In [27]:
df.head(12)

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",...,Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО,rto_lag_1,rto_lag2,rto_mean_lag6
0,0,1,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,22041969.33,NaN,NaN,NaN
1,0,2,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,23268490.57,22041969.33,NaN,NaN
2,0,3,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,24487732.21,23268490.57,22041969.33,NaN
3,0,4,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,23981980.29,24487732.21,23268490.57,NaN
4,0,5,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,26608343.78,23981980.29,24487732.21,NaN
5,0,6,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,26148681.55,26608343.78,23981980.29,NaN
6,0,7,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27292985.79,26148681.55,26608343.78,2.442287e+07
7,0,8,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27712633.36,27292985.79,26148681.55,2.529804e+07
8,0,9,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,24366310.39,27712633.36,27292985.79,2.603873e+07
9,0,10,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27145282.92,24366310.39,27712633.36,2.601849e+07
10,1,1,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,21881376.19,NaN,NaN,NaN
11,1,2,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,24370168.15,21881376.19,NaN,NaN

In [31]:
df_model = df.dropna(subset = ['rto_lag_1', 'rto_lag2', 'rto_mean_lag6'])

In [32]:
df_model.head(12)

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",...,Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО,rto_lag_1,rto_lag2,rto_mean_lag6
6,0,7,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27292985.79,26148681.55,26608343.78,2.442287e+07
7,0,8,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27712633.36,27292985.79,26148681.55,2.529804e+07
8,0,9,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,24366310.39,27712633.36,27292985.79,2.603873e+07
9,0,10,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27145282.92,24366310.39,27712633.36,2.601849e+07
16,1,7,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,19449307.26,24593224.09,25811432.70,2.498825e+07
17,1,8,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,20180451.76,19449307.26,24593224.09,2.458291e+07
18,1,9,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,29966903.89,20180451.76,19449307.26,2.388462e+07
19,1,10,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,32336271.96,29966903.89,20180451.76,2.446957e+07
26,2,7,Средний по возрасту,Маленький,Дубна г,Московская обл,75056,2050,80,144,...,1,1,0,0,7,1,40575848.22,40359880.17,39553586.33,3.666499e+07
27,2,8,Средний по возрасту,Маленький,Дубна г,Московская обл,75056,2050,80,144,...,1,1,0,0,7,1,37722415.42,40575848.22,40359880.17,3.805604e+07
28,2,9,Средний по возрасту,Маленький,Дубна г,Московская обл,75056,2050,80,144,...,1,1,0,0,7,1,37092180.25,37722415.42,40575848.22,3.873594e+07
29,2,10,Средний по возрасту,Маленький,Дубна г,Московская обл,75056,2050,80,144,...,1,1,0,0,7,1,37473470.94,37092180.25,37722415.42,3.866728e+07

In [34]:
train_data = df_model[df_model['Месяц'] <= 9]

In [35]:
test_data = df_model[df_model['Месяц'] == 10]

In [36]:
test_data.head()

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",...,Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО,rto_lag_1,rto_lag2,rto_mean_lag6
9,0,10,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,...,0,0,2,0,10,1,27145282.92,24366310.39,27712633.36,2.601849e+07
19,1,10,Средний по возрасту,Средний,Екатеринбург г,Свердловская обл,1443297,3417,149,204,...,2,3,6,1,9,1,32336271.96,29966903.89,20180451.76,2.446957e+07
29,2,10,Средний по возрасту,Маленький,Дубна г,Московская обл,75056,2050,80,144,...,1,1,0,0,7,1,37473470.94,37092180.25,37722415.42,3.866728e+07
39,3,10,Средний по возрасту,Большой,Подольск г,Московская обл,354166,3460,133,473,...,0,3,4,0,8,1,69136935.96,68517705.13,61614734.64,6.073728e+07
49,4,10,Средний по возрасту,Средний,Москва г,Москва г,12706550,6255,117,302,...,0,11,8,3,11,1,42004513.79,39669637.50,38363685.49,3.992059e+07

In [38]:
df_model.columns

Index(['new_id', 'Месяц', 'Дата открытия, категориальный',
       'Торговая площадь, категориальный', 'Населенный пункт', 'Регион',
       'Численность населения', 'Количество домохозяйств',
       'Трафик пеший, в час', 'Трафик авто, в час',
       'Маркетплейсы, доставки, постаматы (100 м)',
       'Медицинские уч. и аптеки (300 м)', 'Школы (300 м)',
       'Остановки (300 м)', 'Продуктовые магазины (500 м)',
       'Пятерочки (500 м)', 'Количество касс', 'Флаг алкогольной лицензии',
       'РТО', 'rto_lag_1', 'rto_lag2', 'rto_mean_lag6'],
      dtype='object')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206150 entries, 0 to 206149
Data columns (total 22 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   new_id                                     206150 non-null  int64
 1   Месяц                                      206150 non-null  int64
 2   Дата открытия, категориальный              206150 non-null  object
 3   Торговая площадь, категориальный           206150 non-null  object
 4   Населенный пункт                           206150 non-null  object
 5   Регион                                     206150 non-null  object
 6   Численность населения                      206150 non-null  int64
 7   Количество домохозяйств                    206150 non-null  int64
 8   Трафик пеший, в час                        206150 non-null  int64
 9   Трафик авто, в час                         206150 non-null  int64
 10  Маркетплейсы, доставки, постаматы (100 м)  206150 non-null  int64
 11  Медицинские уч. и аптеки (300 м)           206150 non-null  int64
 12  Школы (300 м)                              206150 non-null  int64
 13  Остановки (300 м)                          206150 non-null  int64
 14  Продуктовые магазины (500 м)               206150 non-null  int64
 15  Пятерочки (500 м)                          206150 non-null  int64
 16  Количество касс                            206150 non-null  int64
 17  Флаг алкогольной лицензии                  206150 non-null  int64
 18  РТО                                        206150 non-null  float64
 19  rto_lag_1                                  185535 non-null  float64
 20  rto_lag2                                   164920 non-null  float64
 21  rto_mean_lag6                              82460 non-null   float64
dtypes: float64(4), int64(14), object(4)
memory usage: 34.6+ MB

In [43]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

In [44]:
oe = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=np.nan)

In [47]:
categorical_features = ['Дата открытия, категориальный', 
                        'Торговая площадь, категориальный', 
                        'Населенный пункт', 
                        'Регион']

In [48]:
oe.fit(train_data[categorical_features])

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=nan)

In [49]:
X_train_cat = oe.transform(train_data[categorical_features])

In [50]:
X_test_cat = oe.transform(test_data[categorical_features])

In [52]:
numeric_features = ['Месяц', 'Численность населения', 'Количество домохозяйств', 
                    'Трафик пеший, в час', 'Трафик авто, в час', 
                    'Маркетплейсы, доставки, постаматы (100 м)', 
                    'Медицинские уч. и аптеки (300 м)', 'Школы (300 м)', 
                    'Остановки (300 м)', 'Продуктовые магазины (500 м)', 
                    'Пятерочки (500 м)', 'Количество касс', 
                    'Флаг алкогольной лицензии', 'rto_lag_1', 'rto_lag2', 
                    'rto_mean_lag6']

In [53]:
X_train = np.hstack([train_data[numeric_features].values, X_train_cat])
X_test = np.hstack([test_data[numeric_features].values, X_test_cat])

In [54]:
Y_train = train_data['РТО']
Y_test = test_data['РТО']

In [55]:
from sklearn.tree import DecisionTreeRegressor

In [56]:
tree_model = DecisionTreeRegressor()

In [57]:
tree_model.fit(X_train, Y_train)

DecisionTreeRegressor()

In [58]:
y_pred_tree = tree_model.predict(X_test)

In [59]:
from sklearn.metrics import mean_absolute_percentage_error

In [60]:
mape_tree = mean_absolute_percentage_error(Y_test, y_pred_tree) * 100

In [61]:
mape_tree

9.411885112352476

In [62]:
df_november = df_model[df_model['Месяц'] == 10].copy()

In [63]:
X_november_cat = oe.transform(df_november[categorical_features])

In [64]:
X_november_num = df_november[numeric_features].values

In [65]:
X_november = np.hstack([X_november_num, X_november_cat])

In [66]:
y_november = tree_model.predict(X_november)

In [67]:
submission = pd.DataFrame({'new_id': df_november['new_id'], 'rto': y_november})

In [68]:
print(submission.shape[0])

20615

In [69]:
submission.to_csv('test.csv', index=False)